„ÄÅrefresh_rate: 30 seconds
appenders:
    stdout:
        kind: console
        encoder:
            pattern: "{d(%Y-%m-%d %H:%M:%S)} {h([{l}])} {t} - {m}{n}"
    log_file:
        kind: rolling_file
        policy:
            kind: compound
            trigger:
                kind: size
                limit: 1mb
            roller:
                kind: delete
        path: "logs/app.log"
        append: true
        encoder:
            pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} {t} - {m}{n}"
root:
    level: info
    appenders:
        - stdout
        - log_file